### ISSUE TITLE
Add a waiting time 

### ISSUE THREAD

**Issue by Homavi88** [masterking32/MasterHamsterKombatBot#225]
Please add the waiting time for the next script run, in real time. You could see how much time was left before the launch.
Thk

**Comment by ParsapythonLv** [comment]
Yes, especially if we run the script constantly, it will enter the game continuously, and this is unusual

**Comment by ashwin8454** [comment]
The feature already has the capability to run at random intervals, and it also has a fixed interval setting of 3800 seconds, which is specified in the configuration file.

**Comment by tboy1337** [comment]
I think perhaps what hes trying to say is that there should be a random delay in between accounts being run but currently the bot waits untill all accounts have run before a delay.  I dont think this is intended because there are two delays when the bot reaches the end of the config file which run one after another, this doesnt make sense.
```
[Master HamsterKombat Bot][ERROR] 2024-08-24 10:08:43 Sleeping for 104 seconds because of random delay...
[Master HamsterKombat Bot][ERROR] 2024-08-24 10:10:27 Rechecking all accounts in 312 seconds...
```

**Comment by Fy0urM** [comment]
> Please add the waiting time for the next script run, in real time. You could see how much time was left before the launch. Thk

What exactly do you want to know? How long after the start of the cycle will the next cycle be? Or how long after the end of the current cycle will a new cycle start?
if you are interested in the time after which a new cycle will start after the current cycle ends, you will have to learn math to add a maximum of 7 minutes to the current cycle end time. if you want to know how long it will take to start a new cycle after the current cycle starts, it is technically difficult to do so, because this time consists of the above mentioned pause of a maximum of 7 minutes + time spent on all web requests + random time to wait for the key for each game (because for some games it is different) + pause and wait.
Or do you just want to see in the console output like this
```
[Master HamsterKombat Bot][ERROR] 2024-08-24 20:40:28 Rechecking all accounts in 652 seconds...
[Master HamsterKombat Bot][ERROR] 2024-08-24 20:40:28 Rechecking all accounts in 651 seconds...
[Master HamsterKombat Bot][ERROR] 2024-08-24 20:40:28 Rechecking all accounts in 650 seconds...
[Master HamsterKombat Bot][ERROR] 2024-08-24 20:40:28 Rechecking all accounts in 649 seconds...
[Master HamsterKombat Bot][ERROR] 2024-08-24 20:40:28 Rechecking all accounts in 648 seconds...
[Master HamsterKombat Bot][ERROR] 2024-08-24 20:40:28 Rechecking all accounts in 647 seconds...
[Master HamsterKombat Bot][ERROR] 2024-08-24 20:40:28 Rechecking all accounts in 646 seconds...
[Master HamsterKombat Bot][ERROR] 2024-08-24 20:40:28 Rechecking all accounts in 645 seconds...
```
and so on?
then i want to ask you why do you need this?

**Comment by Homavi88** [comment]
I meant that in the terminal we could see the countdown to the next launch in real time.
