### ISSUE TITLE
покупка новых карточек

### ISSUE THREAD

**Issue by pashva11** [masterking32/MasterHamsterKombatBot#40]
Здравствуйте. 
1. Подскажите, а программа умеет сама покупать новые карточки, которые появляются в разделе Specials - New cards ?
2. Если карточка закрыта и есть условие её открытия - приобрести другую карточку определённого уровня (У новой карточки "fight fight fight" для разблокировки было условие купить карточку "CEO" lvl 17) - программа умеет это делать или нужно сейчас это делать самому (выполнять условие разблокировки карточки)?
3. Ежедневный бонус 5 000 000 при покупке определенных карточек - программа производит расчёт, выгодно или нет сегодня покупать эти три карточки, чтобы заработать 5 миллионов или не производит такого расчёта? 

Заранее благодарю за ответы!

**Comment by Microzibert** [comment]
Hello.

1. Tell me, does the program itself know how to buy new cards that appear in the Specials - New cards section?
2. If the card is closed and there is a condition for opening it - buy another card of a certain level (the new card "fight fight fight" for unlocking had a condition to buy the card "CEO" lvl 17) - the program can do this or you need to do it yourself now (fulfill the unlocking condition cards)?
3. Daily bonus of 5,000,000 when purchasing certain cards - the program makes a calculation whether it is profitable or not to buy these three cards today in order to earn 5 million or does not make such a calculation?
Thanks in advance for your answers!
