### ISSUE TITLE
Bearer Token Update.

### ISSUE THREAD

**Issue by Ashwin3454** [masterking32/MasterHamsterKombatBot#414]

**Comment by Fy0urM** [comment]
proof?

**Comment by Fy0urM** [comment]
it is updated every time you log in to different accounts because most likely the data in the local storage of your browser does not match the account and it is overwritten by the current account and then a new token is requested.
1 account first opening
![image](https://github.com/user-attachments/assets/9ec374ac-628d-494e-b9fd-3a380e3713eb)
1 account second opening
![image](https://github.com/user-attachments/assets/f1ae4bb2-dcea-4dff-8b06-4ba383f3eb30)
1 account third opening
![image](https://github.com/user-attachments/assets/48733dc3-c293-487d-a813-5a3b7782b09f)
2 account, first load
![image](https://github.com/user-attachments/assets/56d83bd3-ca42-4285-bf10-4304018dbcb7)
2 accoundm second load 
![image](https://github.com/user-attachments/assets/e5f017ea-37ba-4427-a518-6eeb3029cc7c)
change back to first account, first load
![image](https://github.com/user-attachments/assets/3fa4194b-f611-47e8-b710-fb43693b976c)
second load
![image](https://github.com/user-attachments/assets/838cd29f-54e0-4970-8fb5-f9e07138417c)

as you can see, the request for `auth-by-telegram-webapp` only happens on the first load when you change your account, this endpoint is what returns the new token

**Comment by Fy0urM** [comment]
or u request this feature?

**Comment by Ashwin3454** [comment]
> or u request this feature?

likely yes. is it possible to update the Bearer token automatically?

**Comment by Fy0urM** [comment]
> likely yes. is it possible to update the Bearer token automatically?

Yes, I am already testing this functionality in my modification, 4 days everything is normal. the thing is that in my implementation to the server is sent previously received from the url query because I could not understand what the hash in the query, and an empty fingerprint, I am not sure that it can be safe so I do not publish this option for now

**Comment by Fy0urM** [comment]
may can try to implement authorization as many bots through web app api, but I am too lazy to deal with it)))))

**Comment by AyomideRaph01** [comment]
> > likely yes. is it possible to update the Bearer token automatically?
> 
> Yes, I am already testing this functionality in my modification, 4 days everything is normal. the thing is that in my implementation to the server is sent previously received from the url query because I could not understand what the hash in the query, and an empty fingerprint, I am not sure that it can be safe so I do not publish this option for now

Please can u share to me

**Comment by Fy0urM** [comment]
> Please can u share to me

u can get it from my test branch https://github.com/Fy0urM/MasterHamsterKombatBot/tree/feature/AutoGetBearer
but, use it u own risk, i'm not responsible if the algorithm turns out to be unsafe.
u need to add a Query parameter to config.py like in config.py.example which you get from the link when you first get the bearer token, you need to insert everything from tgWebAppData all the way to the end
